// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onitpiigijpoiikyhcaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uaXRwaWlnaWpwb2lpa3loY2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTgzNDUsImV4cCI6MjA3MTQ3NDM0NX0.MdvCGRZcPQl8OuduIIHjWc00IfcWQ2mzacSaFUZVcHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});